FROM nginx:latest

LABEL maintainer="Jext Community, https://github.com/jextop"

# copy web files
COPY ./deploy/web/ /usr/share/nginx/html

# config
COPY ./deploy/conf/ /etc/nginx/

WORKDIR /etc/nginx

EXPOSE 8010
