FROM registry.cn-shanghai.aliyuncs.com/jext/starter_admin_base:latest

# web files
COPY ./ /code
WORKDIR /code

# package
RUN cnpm install
RUN npm run build

# copy files
RUN cp -r ./dist/ ./deploy/web/
RUN cp ./public/favicon.png ./deploy/web/

# web files
RUN cp -r ./deploy/web/ /usr/share/nginx/html

# config
RUN cp ./deploy/conf/nginx.conf /etc/nginx/nginx.conf
RUN cp -r ./deploy/conf/conf.d /etc/nginx/conf.d

WORKDIR /etc/nginx

# delete code
RUN rm -rf /code/

EXPOSE 8010
